import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import fs from "fs";
import path from "path";

// 辅助函数：读取目录的 _category_.json
function getCategoryInfo(dirName: string) {
  const categoryPath = path.join(__dirname, "docs", dirName, "_category_.json");
  if (fs.existsSync(categoryPath)) {
    const content = fs.readFileSync(categoryPath, "utf-8");
    return JSON.parse(content);
  }
  return { label: dirName };
}

// 辅助函数：创建一个包含子目录的 category
function createCategory(dirName: string) {
  const info = getCategoryInfo(dirName);
  return {
    type: "category" as const,
    label: info.label,
    link: info.link,
    items: [{ type: "autogenerated" as const, dirName }],
  };
}

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "前端基础",
      collapsed: false,
      items: [
        createCategory("javascript"),
        createCategory("typescript"),
        createCategory("css"),
        createCategory("html"),
        createCategory("regex"),
      ],
    },
    {
      type: "category",
      label: "浏览器与运行时",
      collapsed: false,
      items: [
        createCategory("browser"),
        createCategory("network"),
        createCategory("performance"),
        createCategory("security"),
      ],
    },
    {
      type: "category",
      label: "框架",
      collapsed: true,
      items: [
        createCategory("react"),
        createCategory("vue"),
        createCategory("angular"),
        createCategory("nextjs"),
        createCategory("electron"),
      ],
    },
    {
      type: "category",
      label: "工程化",
      collapsed: true,
      items: [
        createCategory("npm"),
        createCategory("webpack"),
        createCategory("rollup"),
        createCategory("jest"),
        createCategory("practices"),
        createCategory("design-patterns"),
        createCategory("git"),
        createCategory("rust"),
      ],
    },
    {
      type: "category",
      label: "服务端与运维",
      collapsed: true,
      items: [
        createCategory("node"),
        createCategory("express"),
        createCategory("nestjs"),
        createCategory("mysql"),
        createCategory("api"),
        createCategory("graphql"),
        createCategory("docker"),
        createCategory("linux"),
        createCategory("nginx"),
        createCategory("shell"),
      ],
    },
    {
      type: "category",
      label: "算法与数据结构",
      collapsed: true,
      items: [
        createCategory("algorithm"),
        createCategory("data-structures"),
      ],
    },
    {
      type: "category",
      label: "移动端",
      collapsed: true,
      items: [
        createCategory("mobile"),
        createCategory("taro"),
        createCategory("miniprogram"),
      ],
    },
    {
      type: "category",
      label: "AI 开发",
      collapsed: true,
      link: {
        type: "doc",
        id: "ai/README",
      },
      items: [
        {
          type: "category",
          label: "基础概念",
          items: [
            "ai/ai-introduction",
            "ai/machine-learning",
            "ai/deep-learning",
            "ai/large-language-models",
            "ai/llm-fundamentals",
          ],
        },
        {
          type: "category",
          label: "应用开发",
          items: [
            "ai/application-development",
            "ai/llm-selection",
          ],
        },
        {
          type: "category",
          label: "LangChain",
          items: [
            "ai/langchain-introduction",
            "ai/langchain-core-components",
            "ai/langchain-seven-core-components",
            "ai/langchain-components-manual",
          ],
        },
        {
          type: "category",
          label: "LangGraph",
          items: [
            "ai/langgraph-introduction",
            "ai/langgraph-core-concepts",
            "ai/langgraph-build",
            "ai/langgraph-state-checkpoints",
            "ai/langgraph-events-observability",
            "ai/langgraph-memory-conversation",
            "ai/langgraph-tools-integration",
            "ai/langgraph-patterns-architecture",
            "ai/langgraph-testing-evaluation",
            "ai/langgraph-production",
          ],
        },
      ],
    },
    createCategory("samples"),
  ],
};

export default sidebars;
