import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import fs from "fs";
import path from "path";

// 辅助函数：读取目录的 _category_.json
function getCategoryInfo(dirName: string) {
  const categoryPath = path.join(__dirname, "docs", dirName, "_category_.json");
  if (fs.existsSync(categoryPath)) {
    const content = fs.readFileSync(categoryPath, "utf-8");
    return JSON.parse(content);
  }
  return { label: dirName };
}

// 辅助函数：创建一个包含子目录的 category
function createCategory(dirName: string) {
  const info = getCategoryInfo(dirName);
  return {
    type: "category" as const,
    label: info.label,
    link: info.link,
    items: [{ type: "autogenerated" as const, dirName }],
  };
}

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "前端基础",
      collapsed: false,
      items: [
        createCategory("javascript"),
        createCategory("typescript"),
        createCategory("css"),
        createCategory("html"),
        createCategory("regex"),
      ],
    },
    {
      type: "category",
      label: "浏览器与运行时",
      collapsed: false,
      items: [
        createCategory("browser"),
        createCategory("network"),
        createCategory("performance"),
        createCategory("security"),
      ],
    },
    {
      type: "category",
      label: "框架",
      collapsed: true,
      items: [
        createCategory("react"),
        createCategory("vue"),
        createCategory("angular"),
        createCategory("nextjs"),
        createCategory("electron"),
      ],
    },
    {
      type: "category",
      label: "工程化",
      collapsed: true,
      items: [
        createCategory("npm"),
        createCategory("webpack"),
        createCategory("rollupjs"),
        createCategory("jest"),
        createCategory("practices"),
        createCategory("design-patterns"),
        createCategory("git"),
        createCategory("rust"),
      ],
    },
    {
      type: "category",
      label: "服务端与运维",
      collapsed: true,
      items: [
        createCategory("node"),
        createCategory("express"),
        createCategory("nestjs"),
        createCategory("mysql"),
        createCategory("api"),
        createCategory("graphql"),
        createCategory("docker"),
        createCategory("linux"),
        createCategory("nginx"),
        createCategory("shell"),
      ],
    },
    {
      type: "category",
      label: "算法与数据结构",
      collapsed: true,
      items: [
        createCategory("algorithm"),
        createCategory("data-structures"),
      ],
    },
    {
      type: "category",
      label: "移动端",
      collapsed: true,
      items: [
        createCategory("mobile"),
        createCategory("taro"),
        createCategory("miniprogram"),
      ],
    },
    createCategory("ai"),
    createCategory("samples"),
  ],
};

export default sidebars;
