import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 辅助函数：创建一个包含子目录的 category
function createCategory(label: string, dirName: string) {
  return {
    type: "category" as const,
    label,
    items: [{ type: "autogenerated" as const, dirName }],
  };
}

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "前端基础",
      collapsed: false,
      items: [
        createCategory("JavaScript", "javascript"),
        createCategory("TypeScript", "typescript"),
        createCategory("CSS", "css"),
        createCategory("HTML", "html"),
        createCategory("RegEx", "regex"),
      ],
    },
    {
      type: "category",
      label: "浏览器与运行时",
      collapsed: false,
      items: [
        createCategory("浏览器", "browser"),
        createCategory("网络", "network"),
        createCategory("性能", "performance"),
        createCategory("安全", "security"),
      ],
    },
    {
      type: "category",
      label: "框架",
      collapsed: true,
      items: [
        createCategory("React", "react"),
        createCategory("Vue", "vue"),
        createCategory("Angular", "angular"),
        createCategory("Next.js", "nextjs"),
        createCategory("Electron", "electron"),
      ],
    },
    {
      type: "category",
      label: "工程化",
      collapsed: true,
      items: [
        createCategory("NPM", "npm"),
        createCategory("Webpack", "webpack"),
        createCategory("Rollup.js", "rollupjs"),
        createCategory("Jest", "jest"),
        createCategory("最佳实践", "practices"),
        createCategory("设计模式", "design-patterns"),
        createCategory("Git", "git"),
        createCategory("Rust", "rust"),
      ],
    },
    {
      type: "category",
      label: "服务端与运维",
      collapsed: true,
      items: [
        createCategory("Node.js", "node"),
        createCategory("Express", "express"),
        createCategory("NestJS", "nestjs"),
        createCategory("MySQL", "mysql"),
        createCategory("API", "api"),
        createCategory("GraphQL", "graphql"),
        createCategory("Docker", "docker"),
        createCategory("Linux", "linux"),
        createCategory("Nginx", "nginx"),
        createCategory("Shell", "shell"),
      ],
    },
    {
      type: "category",
      label: "算法与数据结构",
      collapsed: true,
      items: [
        createCategory("算法", "algorithm"),
        createCategory("数据结构", "data-structures"),
      ],
    },
    {
      type: "category",
      label: "移动端",
      collapsed: true,
      items: [
        createCategory("移动端", "mobile"),
        createCategory("Taro", "taro"),
        createCategory("小程序", "miniprogram"),
      ],
    },
    createCategory("AI", "ai"),
    createCategory("手写练习", "samples"),
  ],
};

export default sidebars;
